server:
  version: V1.0
  
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/

# security:
#   basic:
#     enabled: true
#   user:
#     name: root
#     password: root

